.class public Lcom/android/flymexx/Settings;
.super Lcom/android/flymexx/SettingsActivity;
.source "Settings.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/android/flymexx/Settings$AccessibilityDaltonizerSettingsActivity;,
        Lcom/android/flymexx/Settings$AccessibilitySettingsActivity;,
        Lcom/android/flymexx/Settings$AccountSettingsActivity;,
        Lcom/android/flymexx/Settings$AccountSyncSettingsActivity;,
        Lcom/android/flymexx/Settings$AdvancedAppsActivity;,
        Lcom/android/flymexx/Settings$AdvancedWifiSettingsActivity;,
        Lcom/android/flymexx/Settings$AllApplicationsActivity;,
        Lcom/android/flymexx/Settings$AndroidBeamSettingsActivity;,
        Lcom/android/flymexx/Settings$ApnEditorActivity;,
        Lcom/android/flymexx/Settings$ApnSettingsActivity;,
        Lcom/android/flymexx/Settings$AppDrawOverlaySettingsActivity;,
        Lcom/android/flymexx/Settings$AppMemoryUsageActivity;,
        Lcom/android/flymexx/Settings$AppNotificationSettingsActivity;,
        Lcom/android/flymexx/Settings$AppOpsSummaryActivity;,
        Lcom/android/flymexx/Settings$AppWriteSettingsActivity;,
        Lcom/android/flymexx/Settings$AutomaticStorageManagerSettingsActivity;,
        Lcom/android/flymexx/Settings$AvailableVirtualKeyboardActivity;,
        Lcom/android/flymexx/Settings$BackgroundCheckSummaryActivity;,
        Lcom/android/flymexx/Settings$BatterySaverSettingsActivity;,
        Lcom/android/flymexx/Settings$BluetoothSettingsActivity;,
        Lcom/android/flymexx/Settings$CaptioningSettingsActivity;,
        Lcom/android/flymexx/Settings$ChooseAccountActivity;,
        Lcom/android/flymexx/Settings$ConfigureNotificationSettingsActivity;,
        Lcom/android/flymexx/Settings$CryptKeeperSettingsActivity;,
        Lcom/android/flymexx/Settings$DataUsageSummaryActivity;,
        Lcom/android/flymexx/Settings$DateTimeSettingsActivity;,
        Lcom/android/flymexx/Settings$DevelopmentSettingsActivity;,
        Lcom/android/flymexx/Settings$DeviceAdminSettingsActivity;,
        Lcom/android/flymexx/Settings$DeviceInfoSettingsActivity;,
        Lcom/android/flymexx/Settings$DeviceSettings;,
        Lcom/android/flymexx/Settings$DisplaySettingsActivity;,
        Lcom/android/flymexx/Settings$DreamSettingsActivity;,
        Lcom/android/flymexx/Settings$FingerprintEnrollSuggestionActivity;,
        Lcom/android/flymexx/Settings$FingerprintSuggestionActivity;,
        Lcom/android/flymexx/Settings$GestureSettingsActivity;,
        Lcom/android/flymexx/Settings$HighPowerApplicationsActivity;,
        Lcom/android/flymexx/Settings$HomeSettingsActivity;,
        Lcom/android/flymexx/Settings$IccLockSettingsActivity;,
        Lcom/android/flymexx/Settings$ImeiInformationActivity;,
        Lcom/android/flymexx/Settings$InputMethodAndLanguageSettingsActivity;,
        Lcom/android/flymexx/Settings$KeyboardLayoutPickerActivity;,
        Lcom/android/flymexx/Settings$LocalePickerActivity;,
        Lcom/android/flymexx/Settings$LocationSettingsActivity;,
        Lcom/android/flymexx/Settings$ManageApplicationsActivity;,
        Lcom/android/flymexx/Settings$ManageAssistActivity;,
        Lcom/android/flymexx/Settings$ManageDomainUrlsActivity;,
        Lcom/android/flymexx/Settings$MemorySettingsActivity;,
        Lcom/android/flymexx/Settings$NightDisplaySettingsActivity;,
        Lcom/android/flymexx/Settings$NotificationAccessSettingsActivity;,
        Lcom/android/flymexx/Settings$NotificationAppListActivity;,
        Lcom/android/flymexx/Settings$NotificationStationActivity;,
        Lcom/android/flymexx/Settings$OtherSoundSettingsActivity;,
        Lcom/android/flymexx/Settings$OverlaySettingsActivity;,
        Lcom/android/flymexx/Settings$PaymentSettingsActivity;,
        Lcom/android/flymexx/Settings$PersonalSettings;,
        Lcom/android/flymexx/Settings$PhysicalKeyboardActivity;,
        Lcom/android/flymexx/Settings$PowerUsageSummaryActivity;,
        Lcom/android/flymexx/Settings$PrintJobSettingsActivity;,
        Lcom/android/flymexx/Settings$PrintSettingsActivity;,
        Lcom/android/flymexx/Settings$PrivacySettingsActivity;,
        Lcom/android/flymexx/Settings$PrivateVolumeForgetActivity;,
        Lcom/android/flymexx/Settings$PrivateVolumeSettingsActivity;,
        Lcom/android/flymexx/Settings$PublicVolumeSettingsActivity;,
        Lcom/android/flymexx/Settings$RoamingSettingsActivity;,
        Lcom/android/flymexx/Settings$RunningServicesActivity;,
        Lcom/android/flymexx/Settings$SavedAccessPointsSettingsActivity;,
        Lcom/android/flymexx/Settings$ScreenLockSuggestionActivity;,
        Lcom/android/flymexx/Settings$SecuritySettingsActivity;,
        Lcom/android/flymexx/Settings$SimSettingsActivity;,
        Lcom/android/flymexx/Settings$SimStatusActivity;,
        Lcom/android/flymexx/Settings$SoundSettingsActivity;,
        Lcom/android/flymexx/Settings$SpellCheckersSettingsActivity;,
        Lcom/android/flymexx/Settings$StatusActivity;,
        Lcom/android/flymexx/Settings$StorageSettingsActivity;,
        Lcom/android/flymexx/Settings$StorageUseActivity;,
        Lcom/android/flymexx/Settings$SystemSettings;,
        Lcom/android/flymexx/Settings$TestingSettingsActivity;,
        Lcom/android/flymexx/Settings$TetherSettingsActivity;,
        Lcom/android/flymexx/Settings$TextToSpeechSettingsActivity;,
        Lcom/android/flymexx/Settings$TimerSwitchSettingsActivity;,
        Lcom/android/flymexx/Settings$TopLevelSettings;,
        Lcom/android/flymexx/Settings$TrustedCredentialsSettingsActivity;,
        Lcom/android/flymexx/Settings$UsageAccessSettingsActivity;,
        Lcom/android/flymexx/Settings$UserDictionarySettingsActivity;,
        Lcom/android/flymexx/Settings$UserSettingsActivity;,
        Lcom/android/flymexx/Settings$VpnSettingsActivity;,
        Lcom/android/flymexx/Settings$VrListenersSettingsActivity;,
        Lcom/android/flymexx/Settings$WallpaperSettingsActivity;,
        Lcom/android/flymexx/Settings$WifiAPITestActivity;,
        Lcom/android/flymexx/Settings$WifiCallingSettingsActivity;,
        Lcom/android/flymexx/Settings$WifiCallingSuggestionActivity;,
        Lcom/android/flymexx/Settings$WifiDisplaySettingsActivity;,
        Lcom/android/flymexx/Settings$WifiInfoActivity;,
        Lcom/android/flymexx/Settings$WifiP2pSettingsActivity;,
        Lcom/android/flymexx/Settings$WifiSettingsActivity;,
        Lcom/android/flymexx/Settings$WirelessSettings;,
        Lcom/android/flymexx/Settings$WirelessSettingsActivity;,
        Lcom/android/flymexx/Settings$WriteSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenAccessSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModeAutomationSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModeAutomationSuggestionActivity;,
        Lcom/android/flymexx/Settings$ZenModeEventRuleSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModeExternalRuleSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModePrioritySettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModeScheduleRuleSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModeSettingsActivity;,
        Lcom/android/flymexx/Settings$ZenModeVisualInterruptionSettingsActivity;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Lcom/android/flymexx/SettingsActivity;-><init>()V

    return-void
.end method
